### ISSUE TITLE
author pages within dossiers and issues return 404

### ISSUE THREAD

**Issue by eharris99** [viewpointmag/viewpointmag#5]
https://viewpointmag.com/author/louis-althusser/
https://viewpointmag.com/author/gopal-balakrishnan/
https://viewpointmag.com/author/kiran-garcha/

today (8/13) we disabled all plugins to see if anything improved. it didn't.

i unclicked “exclude from archives” in category exclusion. and now all author links from dossiers and issues work

the “exclude from archives” broke the wp_query that author.php uses via archives.php

I found post.php in here, it has all the logic of the link in it

/var/www/html/wp-admin/includes

I made copy here

https://gist.github.com/eharris99/becc10cc577e78d52b2c35184a1894d7

i think the UCE is breaking wp_query

https://codex.wordpress.org/Class_Reference/WP_Query#Author_Parameters

I don't see an author.php. I think we may need to make an author.php that uses $curauth as per logic here:

https://codex.wordpress.org/Author_Templates#Setting_Up_for_Author_Information

and 

http://www.wpbeginner.com/wp-themes/how-to-add-a-custom-author-profile-page-to-your-wordpress/

https://developer.wordpress.org/themes/basics/template-hierarchy/

https://codex.wordpress.org/Template_Tags#Author_tags

https://codex.wordpress.org/Function_Reference/the_author

there is an authors.php readable on the wp site

https://viewpointmag.com/wp-admin/theme-editor.php?file=page-templates%2Fauthors.php&theme=path

and an archives.php in /var/www/html/wp-content/themes/path/page-templates

I found widget-most-viewed.php in here:

/var/www/html/wp-content/themes/path/includes

**Comment by peterood** [comment]
Thanks Elise!
